# If not running interactively, don't do anything (leave this at the top of this file)
[[ $- != *i* ]] && return

# All the default Omarchy aliases and functions
# (don't mess with these directly, just overwrite them here!)
source ~/.local/share/omarchy/default/bash/rc

# Add your own exports, aliases, and functions here.
#
# Make an alias for invoking commands you use constantly
# alias p='python'

. "$HOME/.local/share/../bin/env"
fastfetch

export PATH=$PATH:/home/hanka/.spicetify

# Auto-activate venv when in interview-helper directory
cd() {
    builtin cd "$@"
    if [[ -f "venv/bin/activate" && "$VIRTUAL_ENV" == "" ]]; then
        source venv/bin/activate
    fi
}
source ~/.local/share/blesh/ble.sh
function y() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
	yazi "$@" --cwd-file="$tmp"
	IFS= read -r -d '' cwd < "$tmp"
	[ -n "$cwd" ] && [ "$cwd" != "$PWD" ] && builtin cd -- "$cwd"
	rm -f -- "$tmp"
}